export enum TypeListsConstants {
  ACCEPTED_CHALLENGES = 1,
  CREATED_CHALLENGES = 2,
  INVITATION_CHALLENGES = 3,
  VOTING_CHALLENGES = 4,
  VOTING_CHALLENGES_FROM_LIST = 5,
  VOTING_CHALLENGES_FROM_HOME = 6,
}
