export enum VideoLimitConstants {
  MAXDURATION_VIDEO_CHALLENGE = 'MAXDURATION_VIDEO_CHALLENGE',
  MAXDURATION_VIDEO_HABILITY = 'MAXDURATION_VIDEO_HABILITY',
  MAXDURATION_VIDEO_PRESENTATION = 'MAXDURATION_VIDEO_PRESENTATION',
  MAXDURATION_VIDEO_HISTORIES = 'MAXDURATION_VIDEO_HISTORIES',
}
